context:
  name: calcam
  version: "2.17.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/euratom-software/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
    sha256: 61a935f93f8ecef6bf02fcf1e3436e90efd37c0fc27ff5e40caa296e5a2b3d7e

build:
  noarch: python
  script: pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - calcam = calcam:start_gui
  number: 1

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.0
  run:
    - python >=${{ python_min }}
    - matplotlib-base
    - opencv
    - pyqt6
    - scipy
    - vtk-base >=7,!=9.1.*
    - h5py
    - triangle

tests:
  - python:
      imports:
        - calcam
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  homepage: http://euratom-software.github.io/calcam/html/index.html
  summary: Spatial calibration tools for science & engineering camera systems (python module + GUI app).
  repository: https://github.com/euratom-software/calcam/
  documentation: http://euratom-software.github.io/calcam/html/index.html
  license: EUPL-1.1
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ssilburn
    - munechika-koyo
