context:
  name: calcam
  version: "2.16.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/euratom-software/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
    sha256: 5b4ecfdbd6f0a86315d4ba8a190f819bcd2cf789a5a234fa9c04dbf06c73bba8

build:
  noarch: python
  script:
    - if: win
      then: |
        %PYTHON% -m pip install . -vv --no-deps --no-build-isolation
      else: |
        $PYTHON -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - calcam = calcam:start_gui
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=61.0
  run:
    - python >=${{ python_min }}
    - matplotlib-base
    - opencv
    - pyqt
    - scipy
    - vtk-base >=7,<9.3,!=9.1.*
    - h5py
    - triangle

tests:
  - script:
      - python -c "import calcam"
      # - python -m pip check  # Disabled because the triangle package is not recognized by pip
    requirements:
      run:
        - python ${{ python_min }}.*
        - pip
        # qt5 is required for the OpenGL stuff
        # https://github.com/conda-forge/opencv-feedstock/issues/401
        - if: linux
          then:
            - libopencv *=headless*

about:
  homepage: http://euratom-software.github.io/calcam/html/index.html
  summary: Spatial calibration tools for science & engineering camera systems (python module + GUI app).
  repository: https://github.com/euratom-software/calcam/
  documentation: http://euratom-software.github.io/calcam/html/index.html
  license: EUPL-1.1
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ssilburn
    - munechika-koyo
